language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - git checkout package-lock.json
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: >-
        PvOz43kV8DlzIyn1H9/dO/xK4P+3fE5Ei1o+6v7gv+Zs8KHraRrBzj7KtkXjqlv5c/M/tO0px+9ySNMtiP9MnMTXBK60Xkxd7k64EkkiqHQkkhPale1EfMlga7Mm8hQXQhv7h7Z1qrhMVLmDaiHas/ty7ZpeTkKMQbXS4D2ga1I=
    - secure: >-
        jbtiEIANDipVCTdPBX70glFshED4LlRjTppwsO+I9QgJp8dRuvzpSDh3bl+VDaWav16/qeib/S0K01k7raggata1+ow+jcPJARi0zXHSy2C5Al3yiEsPJDrKCQYHUvI6P+Yw2Fd3PK1Jdetpku0D5RZvFUzvxMd+q1s9xF6D5D8=
node_js: node
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test --module-resolution=node --npm
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm -s 'default'; fi
dist: trusty
cache:
  directories:
    - node_modules
